### ISSUE TITLE
Windows: Issue with converting FBX files to USD

### ISSUE THREAD

**Issue by Angps1995** [tappi287/usdzconvert_windows#3]
While trying to convert a fbx to usd using usdzconvert on windows, I encountered this issue: 

**"usdStageWithFbx.py", line 513, in bindMaterials
    UsdShade.Material.Bind(usdMaterial, usdMesh.GetPrim())
AttributeError: type object 'Material' has no attribute 'Bind'**

Anyone has encountered this before and have any potential solutions? Thanks

**Comment by teammixtive** [comment]
Are you able to use the converter at all? I'm trying to use it on Linux, but currently getting this error: 

```
usdUtils.printError("failed to import pxr module. Please add path to USD Python bindings to your PYTHONPATH.")
NameError: name 'usdUtils' is not defined
```

The Pythonpath is set to what it should be. Any inputs?

**Comment by tappi287** [comment]
Hey @Angps1995 building with FBX support would require building with the proprietary FBX SDK which is not intended with this repo. I'm afraid you will need to build USD from scratch for this. But that should by easier with recent versions of USD.

@mixtive Make sure to exactly follow the guide in the ReadMe. run_usd.py will setup the environment for you.
